# Generated by Django 5.2.2 on 2025-06-20 17:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='verification_uuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
