# Generated by Django 5.2.2 on 2025-06-18 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='service_type',
            field=models.CharField(choices=[('teaching', 'Teaching/Tutoring'), ('consulting', 'Academic Consulting'), ('other', 'Other Service')], max_length=20, verbose_name='service type'),
        ),
    ]
