# Generated by Django 5.2.2 on 2025-06-19 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='resource_type',
            field=models.CharField(choices=[('note', 'Lecture Note'), ('book', 'Book/Textbook'), ('exam', 'Exam Paper'), ('other', 'Other')], max_length=20),
        ),
    ]
